version: '3.8'

services:
  # Database Service
  database:
    image: mysql:8.0
    container_name: wms-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-warehouse_wms}
      MYSQL_USER: ${DB_USER:-wms_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wmspassword}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - wms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wms-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://${DB_USER:-wms_user}:${DB_PASSWORD:-wmspassword123}@database:3306/${DB_NAME:-warehouse_wms}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      PORT: 5000
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      database:
        condition: service_healthy
    networks:
      - wms-network
    command: sh -c "npx prisma migrate deploy && npx ts-node src/index.ts"

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wms-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    depends_on:
      - backend
    networks:
      - wms-network

  # Certbot SSL Certificate Service
  certbot:
    image: certbot/certbot:latest
    container_name: wms-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    depends_on:
      - frontend
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@qgocargo.cloud --agree-tos --no-eff-email -d qgocargo.cloud -d www.qgocargo.cloud

  # Auto Git Commit Service (File Watcher)
  git-watcher:
    image: alpine:latest
    container_name: wms-git-watcher
    restart: unless-stopped
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    command: sh -c "apk add --no-cache git inotify-tools && sh /workspace/scripts/git-auto-commit.sh"
    networks:
      - wms-network

  # Automated Database Backup (runs daily at 2 AM)
  db-backup:
    image: alpine:latest
    container_name: wms-db-backup
    restart: unless-stopped
    volumes:
      - ./database-backups:/backups
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      BACKUP_SCHEDULE: "0 2 * * *"  # Daily at 2 AM
      KEEP_DAYS: 7
    command: sh -c "
      apk add --no-cache docker-cli mysql-client dcron &&
      echo '0 2 * * * docker exec wms-database mysqldump -u root -prootpassword warehouse_wms | gzip > /backups/backup_$(date +\\%Y\\%m\\%d_\\%H\\%M\\%S).sql.gz && find /backups -name \"backup_*.sql.gz\" -mtime +7 -delete && echo \"[$(date)] Backup completed\"' > /etc/crontabs/root &&
      crond -f -l 2
      "
    networks:
      - wms-network
    depends_on:
      - database

networks:
  wms-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  certbot-etc:
    driver: local
  certbot-var:
    driver: local
  web-root:
    driver: local
