version: '3.8'

services:
  # Database Service (same as production)
  database:
    image: mysql:8.0
    container_name: wms-database-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-warehouse_wms}
      MYSQL_USER: ${DB_USER:-wms_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wmspassword}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - wms-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Development Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: wms-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://${DB_USER:-wms_user}:${DB_PASSWORD:-wmspassword}@database:3306/${DB_NAME:-warehouse_wms}
      JWT_SECRET: ${JWT_SECRET:-dev-secret-key}
      PORT: 5000
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      database:
        condition: service_healthy
    networks:
      - wms-network-dev

  # Frontend Development Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wms-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - wms-network-dev

  # Auto Git Commit Service
  git-watcher:
    image: alpine:latest
    container_name: wms-git-watcher-dev
    restart: unless-stopped
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sh -c "apk add --no-cache git inotify-tools && sh /workspace/scripts/git-auto-commit.sh"
    networks:
      - wms-network-dev

networks:
  wms-network-dev:
    driver: bridge

volumes:
  mysql_data_dev:
    driver: local
