server {
    listen 80 default_server;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 100M;
    
    location /uploads/ {
        proxy_pass http://wms-backend:5000/uploads/;
    }
    
    location /api {
        proxy_pass http://wms-backend:5000;
    }
    
    location / {
        try_files $uri /index.html;
    }
}
