CREATE TABLE material_issue_history (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  issueId VARCHAR(191) NULL,
  action VARCHAR(50) NOT NULL,
  jobId VARCHAR(191) NULL,
  materialId VARCHAR(191) NOT NULL,
  materialName VARCHAR(255) NOT NULL,
  materialSku VARCHAR(100) NOT NULL,
  quantity INT NOT NULL,
  previousQty INT NULL,
  unitCost DOUBLE NOT NULL,
  totalCost DOUBLE NOT NULL,
  rackId VARCHAR(191) NULL,
  rackCode VARCHAR(100) NULL,
  notes TEXT NULL,
  reason TEXT NULL,
  performedById VARCHAR(191) NOT NULL,
  performedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  companyId VARCHAR(191) NOT NULL,
  INDEX idx_issueId (issueId),
  INDEX idx_companyId (companyId),
  INDEX idx_performedAt (performedAt),
  INDEX idx_materialId (materialId)
);
