USE warehouse_wms;
CREATE TABLE IF NOT EXISTS shipment_dimensions (
  id varchar(191) NOT NULL,
  shipmentId varchar(191) NOT NULL,
  companyId varchar(191) NOT NULL,
  label varchar(191) NULL,
  itemType varchar(191) NOT NULL DEFAULT 'BOX',
  quantity int NOT NULL DEFAULT 1,
  length double NOT NULL,
  width double NOT NULL,
  height double NOT NULL,
  cbm double NOT NULL,
  totalCBM double NOT NULL,
  weight double NULL,
  totalWeight double NULL,
  rackId varchar(191) NULL,
  status varchar(191) NOT NULL DEFAULT 'PENDING',
  assignedAt datetime(3) NULL,
  releasedAt datetime(3) NULL,
  notes text NULL,
  createdAt datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  INDEX idx_shipment (shipmentId),
  INDEX idx_company (companyId),
  INDEX idx_rack (rackId),
  INDEX idx_status (status),
  CONSTRAINT fk_dim_shipment FOREIGN KEY (shipmentId) REFERENCES shipments(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_dim_rack FOREIGN KEY (rackId) REFERENCES racks(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
