const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function safeExec(cmd) {
  try {
    return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'], timeout: 5000 }).toString().trim();
  } catch {
    return null;
  }
}

function readVersionFromEnv() {
  return process.env.APP_VERSION || null;
}

function readVersionFromFile(filepath) {
  try {
    if (fs.existsSync(filepath)) {
      return fs.readFileSync(filepath, 'utf8').trim().replace(/^v/, '');
    }
  } catch {}
  return null;
}

const scriptsDir = path.resolve(__dirname);
const backendRoot = path.resolve(scriptsDir, '..');
const repoRoot = path.resolve(backendRoot, '..');
const versionTsPath = path.join(backendRoot, 'src', 'config', 'version.ts');

// --- DETERMINE VERSION ---
let version = '1.0.0';
const gitTag = safeExec('git describe --tags --abbrev=0 2>/dev/null');
if (gitTag && /^v?\d+\.\d+\.\d+/.test(gitTag)) {
  version = gitTag.replace(/^v/, '');
} else {
  version = readVersionFromEnv()
    || readVersionFromFile(path.join(backendRoot, 'VERSION'))
    || readVersionFromFile(path.join(repoRoot, 'VERSION'))
    || '1.0.0';
}

const commitCount = process.env.COMMIT_COUNT || safeExec('git rev-list --count HEAD 2>/dev/null') || '0';
const fullVersion = `v${version}+build.${commitCount}`;
const commitHash = process.env.COMMIT_HASH || safeExec('git rev-parse --short HEAD') || 'local-dev';
const commitMessage = process.env.COMMIT_MESSAGE || safeExec('git log -1 --pretty=%s') || 'local-build';
const branch = process.env.BRANCH || safeExec('git rev-parse --abbrev-ref HEAD') || 'unknown';

const environment = process.env.DEPLOYMENT_STAGE ||
  (branch === 'staging' ? 'staging' :
   branch === 'stable/prisma-mysql-production' ? 'production' : 'development');

const content = `/**
 * Version Configuration - AUTO-GENERATED
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-version.js
 * Run 'npm run build' or 'node scripts/generate-version.js' to update
 */

export const APP_VERSION = '${fullVersion}';

export const COMMIT_MESSAGE = '${commitMessage.replace(/'/g, "\\'")}';

export const getVersionInfo = () => {
  return {
    version: APP_VERSION,
    environment: process.env.NODE_ENV || 'development',
    stage: '${environment}',
    buildDate: new Date().toISOString(),
    commitHash: '${commitHash}',
    commitMessage: COMMIT_MESSAGE,
    branch: '${branch}',
    commitCount: '${commitCount}',
    timestamp: Date.now(),
  };
};

export const logVersionInfo = () => {
  const info = getVersionInfo();
  console.log(\`
╔════════════════════════════════════════╗
║  🚀 WMS Backend Version: \${info.version}        ║
║  Stage: \${info.stage.toUpperCase()}                     ║
║  Branch: \${info.branch}                 ║
║  Build Date: \${new Date(info.buildDate).toLocaleDateString()}      ║
╚════════════════════════════════════════╝
  \`);
};
`;

fs.writeFileSync(versionTsPath, content);
console.log(`[generate-version] Wrote ${versionTsPath} -> ${fullVersion} (${environment}, branch: ${branch})`);
