-- CreateTable
CREATE TABLE "template_settings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "companyName" TEXT,
    "companyLogo" TEXT,
    "companyAddress" TEXT,
    "companyPhone" TEXT,
    "companyEmail" TEXT,
    "companyWebsite" TEXT,
    "companyLicense" TEXT,
    "invoiceTemplateType" TEXT,
    "invoiceTitle" TEXT,
    "invoiceShowLogo" BOOLEAN,
    "invoiceShowAddress" BOOLEAN,
    "invoiceShowPhone" BOOLEAN,
    "invoiceShowEmail" BOOLEAN,
    "invoiceShowWebsite" BOOLEAN,
    "invoiceShowLicense" BOOLEAN,
    "invoiceShowFooter" BOOLEAN,
    "invoiceHeaderBg" TEXT,
    "invoiceHeaderText" TEXT,
    "invoiceFooterText" TEXT,
    "invoiceTerms" TEXT,
    "invoiceShowBorders" BOOLEAN,
    "invoiceShowGrid" BOOLEAN,
    "invoiceTableStyle" TEXT,
    "invoiceFontSize" TEXT,
    "invoicePaperSize" TEXT,
    "invoicePrimaryColor" TEXT,
    "invoiceSecondaryColor" TEXT,
    "invoiceAccentColor" TEXT,
    "invoiceDangerColor" TEXT,
    "releaseNoteTemplate" TEXT,
    "releaseNoteTitle" TEXT,
    "releaseNoteHeaderBg" TEXT,
    "releaseNoteShowLogo" BOOLEAN,
    "releaseShowShipment" BOOLEAN,
    "releaseShowStorage" BOOLEAN,
    "releaseShowItems" BOOLEAN,
    "releaseShowCollector" BOOLEAN,
    "releaseShowCharges" BOOLEAN,
    "releaseShowPhotos" BOOLEAN,
    "releaseShowTerms" BOOLEAN,
    "releaseShowSignatures" BOOLEAN,
    "releaseTerms" TEXT,
    "releaseFooterText" TEXT,
    "releasePrimaryColor" TEXT,
    "printMarginTop" INTEGER,
    "printMarginBottom" INTEGER,
    "printMarginLeft" INTEGER,
    "printMarginRight" INTEGER,
    "language" TEXT,
    "dateFormat" TEXT,
    "timeFormat" TEXT,
    "currencySymbol" TEXT,
    "currencyPosition" TEXT,
    "customField1Label" TEXT,
    "customField1Value" TEXT,
    "customField2Label" TEXT,
    "customField2Value" TEXT,
    "customField3Label" TEXT,
    "customField3Value" TEXT,
    "requireStaffSignature" BOOLEAN,
    "requireClientSignature" BOOLEAN,
    "signatureHeight" INTEGER,
    "showQRCode" BOOLEAN,
    "qrCodePosition" TEXT,
    "qrCodeSize" INTEGER,
    "showWatermark" BOOLEAN,
    "watermarkText" TEXT,
    "watermarkOpacity" REAL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "template_settings_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "template_settings_companyId_key" ON "template_settings"("companyId");
