ALTER TABLE racks 
ADD COLUMN category VARCHAR(255) NULL,
ADD COLUMN length DOUBLE NULL,
ADD COLUMN width DOUBLE NULL,
ADD COLUMN height DOUBLE NULL,
ADD COLUMN dimensionUnit VARCHAR(50) NOT NULL DEFAULT 'METERS';
