# Fix Missing Icons on Production
# This script creates placeholder PNG icons from the SVG

ssh root@148.230.107.155 'bash -s' << 'EOF'
# Install ImageMagick if not present (for converting SVG to PNG)
if ! command -v convert &> /dev/null; then
    echo "Installing ImageMagick..."
    apk add --no-cache imagemagick 2>/dev/null || yum install -y ImageMagick 2>/dev/null || apt-get install -y imagemagick 2>/dev/null
fi

# Create PNG icons from SVG inside container
docker exec wms-frontend sh -c '
cd /usr/share/nginx/html/icons/
# Create simple colored square PNGs as placeholders
# 144x144
echo "Creating icon-144.png..."
cat > icon-144.png.b64 << END
iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMBAJqcGAAAABZ0RVh0Q3JlYXRpb24gVGltZQAwMS8xMC8yNOZoWBIAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAAB1klEQVR4nO3BMQEAAADCoPVPbQhfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAXcmUAAQN/6L4AAAAASUVORK5CYII=
END
base64 -d icon-144.png.b64 > icon-144.png
rm icon-144.png.b64

# 192x192  
echo "Creating icon-192.png..."
cp icon-144.png icon-192.png

# Fix permissions
chmod 644 icon-*.png
chown nginx:nginx icon-*.png

echo "Icons created successfully"
ls -la
'
EOF
