/**
 * Version Configuration - AUTO-GENERATED
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-version.js
 * Run 'npm run build' or 'node scripts/generate-version.js' to update
 */

export const APP_VERSION = 'v2.4.0+build.977';

export const COMMIT_MESSAGE = 'fix: Shipments crash - createdBy object render fix + mapper updates';

export const getVersionInfo = () => {
  return {
    version: APP_VERSION,
    environment: process.env.NODE_ENV || 'development',
    stage: 'staging',
    buildDate: new Date().toISOString(),
    commitHash: '27553b4df',
    commitMessage: COMMIT_MESSAGE,
    branch: 'staging',
    commitCount: '977',
    timestamp: Date.now(),
  };
};

export const logVersionInfo = () => {
  const info = getVersionInfo();
  console.log(`
╔════════════════════════════════════════╗
║  🚀 WMS Backend Version: ${info.version}        ║
║  Stage: ${info.stage.toUpperCase()}                     ║
║  Branch: ${info.branch}                 ║
║  Build Date: ${new Date(info.buildDate).toLocaleDateString()}      ║
╚════════════════════════════════════════╝
  `);
};
