-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_shipment_settings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "requireClientEmail" BOOLEAN NOT NULL DEFAULT false,
    "requireClientPhone" BOOLEAN NOT NULL DEFAULT true,
    "requireEstimatedValue" BOOLEAN NOT NULL DEFAULT false,
    "requirePhotos" BOOLEAN NOT NULL DEFAULT false,
    "autoGenerateQR" BOOLEAN NOT NULL DEFAULT true,
    "qrCodePrefix" TEXT NOT NULL DEFAULT 'SHP',
    "showClientAddress" BOOLEAN NOT NULL DEFAULT true,
    "requireClientAddress" BOOLEAN NOT NULL DEFAULT false,
    "showDescription" BOOLEAN NOT NULL DEFAULT true,
    "requireDescription" BOOLEAN NOT NULL DEFAULT false,
    "showReferenceId" BOOLEAN NOT NULL DEFAULT true,
    "requireReferenceId" BOOLEAN NOT NULL DEFAULT false,
    "showNotes" BOOLEAN NOT NULL DEFAULT true,
    "requireNotes" BOOLEAN NOT NULL DEFAULT false,
    "showWarehouseMode" BOOLEAN NOT NULL DEFAULT true,
    "showShipperDetails" BOOLEAN NOT NULL DEFAULT true,
    "requireShipperDetails" BOOLEAN NOT NULL DEFAULT true,
    "showConsigneeDetails" BOOLEAN NOT NULL DEFAULT true,
    "requireConsigneeDetails" BOOLEAN NOT NULL DEFAULT true,
    "showWeight" BOOLEAN NOT NULL DEFAULT true,
    "requireWeight" BOOLEAN NOT NULL DEFAULT false,
    "showDimensions" BOOLEAN NOT NULL DEFAULT true,
    "requireDimensions" BOOLEAN NOT NULL DEFAULT false,
    "showStorageType" BOOLEAN NOT NULL DEFAULT true,
    "showSpecialInstructions" BOOLEAN NOT NULL DEFAULT true,
    "showEstimatedDays" BOOLEAN NOT NULL DEFAULT true,
    "requireEstimatedDays" BOOLEAN NOT NULL DEFAULT false,
    "defaultEstimatedDays" INTEGER NOT NULL DEFAULT 30,
    "defaultStorageType" TEXT NOT NULL DEFAULT 'PERSONAL',
    "allowMultipleRacks" BOOLEAN NOT NULL DEFAULT false,
    "requireRackAssignment" BOOLEAN NOT NULL DEFAULT false,
    "autoAssignRack" BOOLEAN NOT NULL DEFAULT false,
    "notifyOnLowCapacity" BOOLEAN NOT NULL DEFAULT true,
    "lowCapacityThreshold" INTEGER NOT NULL DEFAULT 80,
    "requireReleaseApproval" BOOLEAN NOT NULL DEFAULT false,
    "releaseApproverRole" TEXT NOT NULL DEFAULT 'MANAGER',
    "requireReleasePhotos" BOOLEAN NOT NULL DEFAULT false,
    "requireIDVerification" BOOLEAN NOT NULL DEFAULT true,
    "generateReleaseInvoice" BOOLEAN NOT NULL DEFAULT true,
    "autoSendInvoiceEmail" BOOLEAN NOT NULL DEFAULT false,
    "storageRatePerDay" REAL NOT NULL DEFAULT 2.0,
    "storageRatePerBox" REAL NOT NULL DEFAULT 0.0,
    "chargePartialDay" BOOLEAN NOT NULL DEFAULT true,
    "minimumChargeDays" INTEGER NOT NULL DEFAULT 1,
    "releaseHandlingFee" REAL NOT NULL DEFAULT 0.0,
    "releasePerBoxFee" REAL NOT NULL DEFAULT 0.0,
    "releaseTransportFee" REAL NOT NULL DEFAULT 0.0,
    "notifyClientOnIntake" BOOLEAN NOT NULL DEFAULT true,
    "notifyClientOnRelease" BOOLEAN NOT NULL DEFAULT true,
    "notifyOnStorageAlert" BOOLEAN NOT NULL DEFAULT true,
    "storageAlertDays" INTEGER NOT NULL DEFAULT 30,
    "enableCustomFields" BOOLEAN NOT NULL DEFAULT true,
    "requiredCustomFields" TEXT,
    "allowPartialRelease" BOOLEAN NOT NULL DEFAULT true,
    "partialReleaseMinBoxes" INTEGER NOT NULL DEFAULT 1,
    "requirePartialApproval" BOOLEAN NOT NULL DEFAULT false,
    "requireReleaseSignature" BOOLEAN NOT NULL DEFAULT true,
    "requireCollectorID" BOOLEAN NOT NULL DEFAULT true,
    "allowProxyCollection" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "shipment_settings_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_shipment_settings" ("allowMultipleRacks", "allowPartialRelease", "allowProxyCollection", "autoAssignRack", "autoGenerateQR", "autoSendInvoiceEmail", "chargePartialDay", "companyId", "createdAt", "defaultStorageType", "enableCustomFields", "generateReleaseInvoice", "id", "lowCapacityThreshold", "minimumChargeDays", "notifyClientOnIntake", "notifyClientOnRelease", "notifyOnLowCapacity", "notifyOnStorageAlert", "partialReleaseMinBoxes", "qrCodePrefix", "releaseApproverRole", "releaseHandlingFee", "releasePerBoxFee", "releaseTransportFee", "requireClientEmail", "requireClientPhone", "requireCollectorID", "requireEstimatedValue", "requireIDVerification", "requirePartialApproval", "requirePhotos", "requireRackAssignment", "requireReleaseApproval", "requireReleasePhotos", "requireReleaseSignature", "requiredCustomFields", "storageAlertDays", "storageRatePerBox", "storageRatePerDay", "updatedAt") SELECT "allowMultipleRacks", "allowPartialRelease", "allowProxyCollection", "autoAssignRack", "autoGenerateQR", "autoSendInvoiceEmail", "chargePartialDay", "companyId", "createdAt", "defaultStorageType", "enableCustomFields", "generateReleaseInvoice", "id", "lowCapacityThreshold", "minimumChargeDays", "notifyClientOnIntake", "notifyClientOnRelease", "notifyOnLowCapacity", "notifyOnStorageAlert", "partialReleaseMinBoxes", "qrCodePrefix", "releaseApproverRole", "releaseHandlingFee", "releasePerBoxFee", "releaseTransportFee", "requireClientEmail", "requireClientPhone", "requireCollectorID", "requireEstimatedValue", "requireIDVerification", "requirePartialApproval", "requirePhotos", "requireRackAssignment", "requireReleaseApproval", "requireReleasePhotos", "requireReleaseSignature", "requiredCustomFields", "storageAlertDays", "storageRatePerBox", "storageRatePerDay", "updatedAt" FROM "shipment_settings";
DROP TABLE "shipment_settings";
ALTER TABLE "new_shipment_settings" RENAME TO "shipment_settings";
CREATE UNIQUE INDEX "shipment_settings_companyId_key" ON "shipment_settings"("companyId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
